const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync('google-glass.less', 'utf8');
assert.match(source, /@glass-blur:\s*24px/);
assert.match(source, /@radius:\s*20px/);
assert.doesNotMatch(source, /url\s*\(/i);

assert.match(source, /radial-gradient/);
assert.match(source, /--page:\s*#101012/);
assert.match(source, /--glass:\s*rgba\(34,\s*34,\s*38,\s*0\.72\)/);
assert.match(source, /--link:\s*#0a84ff/);
assert.match(source, /--text:\s*#f5f5f7/);
assert.match(source, /--muted:\s*#a1a1a6/);
assert.match(source, /saturate\(140%\)/);
assert.match(source, /linear-gradient\([\s\S]*var\(--glass-highlight\)/);
assert.match(source, /#rso\s*>\s*\.MjjYud:hover[\s\S]*background:\s*var\(--glass-hover\)/);
assert.doesNotMatch(source, /transform:\s*scale/);
assert.match(source, /\.glass-panel\(\)[\s\S]*background:\s*var\(--glass\)/);
assert.match(source, /#rso\s*>\s*\.MjjYud[\s\S]*\.glass-panel\(\);/);
assert.match(source, /focus-visible/);
assert.match(source, /@supports not[\s\S]*backdrop-filter/);
assert.doesNotMatch(source, /display:\s*none/);
assert.doesNotMatch(source, /visibility:\s*hidden/);
assert.match(source, /@media \(min-width:\s*@breakpoint\)/);
assert.match(source, /#rcnt[\s\S]*width:\s*min\(calc\(100% - 48px\),\s*1440px\)/);
assert.match(source, /#center_col[\s\S]*grid-column:\s*1\s*\/\s*-1/);
assert.match(source, /#rso[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/);
assert.match(source, /#rso:not\(:has\(> div:not\(\.MjjYud\):not\(\.g\):not\(\.ULSxyf\):not\(\.kp-wholepage\)\)\)/);
assert.match(source, /#rso\s*>\s*\.MjjYud,[\s\S]*?\{\s*display:\s*block;/);
assert.match(source, /@media \(min-width:\s*@wide-breakpoint\)/);
assert.match(source, /@media \(max-width:\s*\(@breakpoint - 1px\)\)/);
assert.match(source, /@media \(max-width:[\s\S]*#rcnt\s*\{[\s\S]*display:\s*block/);
assert.match(source, /@media \(max-width:[\s\S]*#rso\s*\{[\s\S]*display:\s*block/);
assert.doesNotMatch(source, /overflow-x:\s*clip/);
assert.match(source, /prefers-reduced-motion:\s*reduce/);
assert.doesNotMatch(source, /prefers-reduced-motion[\s\S]*\*,/);
assert.doesNotMatch(source, /^a,\s*\na:visited/m);
assert.doesNotMatch(source, /#searchform[\s\S]*position:\s*sticky/);
assert.doesNotMatch(source, /#botstuff\s*\{[\s\S]*\.glass-panel\(\);/);
assert.doesNotMatch(source, /#rso[^{}]*:not\([^{}]*\)\s*\{[^}]*height:\s*0/s);
assert.doesNotMatch(source, /@import/i);
assert.doesNotMatch(source, /position:\s*fixed/);
console.log('theme contract ok');
